[package]
name = "nannou"
version ="0.16.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A Creative Coding Framework for Rust."
readme = "README.md"
keywords = ["creative", "sketch", "graphics", "audio"]
license = "MIT"
repository = "https://github.com/nannou-org/nannou.git"
homepage = "https://github.com/nannou-org/nannou"
edition = "2018"

[features]
default = ["notosans"]

[dependencies]
conrod_core = "0.73"
conrod_wgpu = "0.73"
conrod_winit = "0.72"
daggy = "0.6"
find_folder = "0.3"
futures = { version = "0.3", features = ["executor", "thread-pool"] }
image = "0.23"
instant = "0.1.9"
lyon = "0.15"
nannou_core = { version = "0.16.0", path = "../nannou_core", features = ["std", "serde"] }
noise = "0.6"
notosans = { version = "0.1", optional = true }
num_cpus = "1"
pennereq = "0.3"
rusttype = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.5"
walkdir = "2"
wgpu_upstream = { version = "0.8", package = "wgpu" }
winit = "0.24"
